# Gradle JVM ????
org.gradle.jvmargs=-Xmx2048m -XX:+UseG1GC

# ????
org.gradle.parallel=true
org.gradle.workers.max=4

# ????
org.gradle.caching=true
org.gradle.build.cache.enabled=true

# ??????
org.gradle.vfs.watch=true

# ????
org.gradle.warning.mode=all

# ??????
projectGroup=com.night
projectVersion=0.0.1-SNAPSHOT
javaVersion=21

