-- sql
-- enable UUID generation (pgcrypto provides gen_random_uuid)
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- 用户表
CREATE TABLE user_info (
                           id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                           uid uuid DEFAULT gen_random_uuid(),
                           username varchar(100) NOT NULL UNIQUE,
                           email varchar(255) NOT NULL UNIQUE,
                           password_hash varchar(255) NOT NULL,
                           full_name varchar(255),
                           is_active boolean NOT NULL DEFAULT true,
                           created_at timestamptz NOT NULL DEFAULT now(),
                           updated_at timestamptz NOT NULL DEFAULT now()
);

-- 产品表
CREATE TABLE products (
                          id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                          name varchar(255) NOT NULL,
                          description text,
                          price decimal(10,2) NOT NULL,
                          stock integer NOT NULL,
                          category varchar(255) NOT NULL,
                          image_url varchar(500),
                          is_active boolean NOT NULL DEFAULT true,
                          created_at timestamptz NOT NULL DEFAULT now(),
                          updated_at timestamptz NOT NULL DEFAULT now()
);

-- 订单表
CREATE TABLE orders (
                        id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                        order_number varchar(50) UNIQUE,
                        user_id bigint NOT NULL,
                        total_amount decimal(10,2),
                        status varchar(50) NOT NULL,
                        shipping_address text,
                        created_at timestamptz NOT NULL DEFAULT now(),
                        updated_at timestamptz NOT NULL DEFAULT now(),
                        FOREIGN KEY (user_id) REFERENCES user_info(id)
);

-- 角色表
CREATE TABLE role_info (
                           id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                           name varchar(100) NOT NULL UNIQUE,
                           description text,
                           created_at timestamptz NOT NULL DEFAULT now(),
                           updated_at timestamptz NOT NULL DEFAULT now()
);

-- 用户角色关联表
CREATE TABLE user_role (
                           user_id integer NOT NULL,
                           role_id integer NOT NULL,
                           assigned_at timestamptz NOT NULL DEFAULT now(),
                           PRIMARY KEY (user_id, role_id),
                           FOREIGN KEY (user_id) REFERENCES user_info(id) ON DELETE CASCADE,
                           FOREIGN KEY (role_id) REFERENCES role_info(id) ON DELETE CASCADE
);