-- sql
-- enable UUID generation (pgcrypto provides gen_random_uuid)
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- 用户表
CREATE TABLE user_info (
                           id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                           uid uuid DEFAULT gen_random_uuid(),
                           role_id bigint,
                           username varchar(100) NOT NULL UNIQUE,
                           email varchar(255) NOT NULL UNIQUE,
                           password_hash varchar(255) NOT NULL,
                           full_name varchar(255),
                           is_active boolean NOT NULL DEFAULT true,
                           created_at timestamptz NOT NULL DEFAULT now(),
                           updated_at timestamptz NOT NULL DEFAULT now()
);

-- 产品表
CREATE TABLE products (
                          id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                          name varchar(255) NOT NULL,
                          description text,
                          price decimal(10,2) NOT NULL,
                          stock integer NOT NULL,
                          category varchar(255) NOT NULL,
                          image_url varchar(500),
                          is_active boolean NOT NULL DEFAULT true,
                          created_at timestamptz NOT NULL DEFAULT now(),
                          updated_at timestamptz NOT NULL DEFAULT now()
);

-- 订单表
CREATE TABLE orders (
                        id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                        order_number varchar(50) UNIQUE,
                        user_id bigint NOT NULL,
                        total_amount decimal(10,2),
                        status varchar(50) NOT NULL,
                        shipping_address text,
                        created_at timestamptz NOT NULL DEFAULT now(),
                        updated_at timestamptz NOT NULL DEFAULT now(),
                        FOREIGN KEY (user_id) REFERENCES user_info(id)
);

-- 角色表
CREATE TABLE role_info (
                           id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                           name varchar(100) NOT NULL UNIQUE,
                           description text,
                           created_at timestamptz NOT NULL DEFAULT now(),
                           updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE menu_info (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    parent_id bigint DEFAULT 0,             -- 父菜单ID
    title varchar(50) NOT NULL,             -- 菜单显示名称
    name varchar(50),                       -- 路由名称
    path varchar(255),                      -- 路由路径
    component varchar(255),                 -- 前端组件路径
    perms varchar(100),                     -- 权限标识，如 'user:list'
    icon varchar(50),                       -- 图标
    sort_order int4 DEFAULT 0,              -- 排序
    menu_type char(1) DEFAULT 'M',          -- M:目录, C:菜单, F:按钮
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);
CREATE INDEX idx_menu_pid ON menu_info(parent_id);

-- 4. 角色-菜单关联表 (逻辑关联)
CREATE TABLE role_menu (
    role_id bigint NOT NULL,
    menu_id bigint NOT NULL,
    PRIMARY KEY (role_id, menu_id)
);
CREATE INDEX idx_rm_role_id ON role_menu(role_id);